#!/usr/bin/env bash

set -e
source ../common/utils.sh
DATE=`date '+%Y-%m-%d %H:%M:%S'`
GENERATESTRING="# Generated by install_ssh_server.sh ${DATE}"


sudo apt install openssh-server -y

# RENDER TEMPLATE templates/sshd_config.conf INTO /etc/ssh/sshd_config OVERRIDE

mkdir -p ~/.ssh/
chmod 700 ~/.ssh/
# RENDER TEMPLATE templates/authorized_keys INTO ~/.ssh/authorized_keys IGNORE

ME=$(whoami)
sudo chown ${ME}:${ME} ~/.ssh/authorized_kedjango ys