version: '2'
services:
  some-mongo:
    image: "mongo:3"
    volumes:
      - /opt/graylog/data/mongo:/data/db
  some-elasticsearch:
    image: "elasticsearch:5"
    environment:
      http.host: 0.0.0.0
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: "-Xms1024m -Xmx1024m"
    volumes:
      - /opt/graylog/data/elasticsearch:/usr/share/elasticsearch/data
  graylog:
    image: graylog/graylog:2.4
    volumes:
      - /opt/graylog/data/journal:/usr/share/graylog/data/journal
      #- /opt/graylog/config:/usr/share/graylog/data/config
    environment:
      GRAYLOG_PASSWORD_SECRET: ${GRAYLOG_PASSWORD_SECRET}
      # admin // ${GRAYLOG_ADMIN_PASSWORD}
      GRAYLOG_ROOT_PASSWORD_SHA2: ${GRAYLOG_ADMIN_PASSWORD_SHA2}
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
    links:
      - some-mongo:mongo
      - some-elasticsearch:elasticsearch
    ports:
      - "9000:9000"
      - "12201:12201"
      - "12201:12201/udp"
      - "1514:1514"
      - "1514:1514/udp"
      - "5044:5044"
      - "5044:5044/udp"
      - "12301:12301"
      - "12301:12301/udp"
      - "12302:12302"
      - "12302:12302/udp"